language: ruby

before_script:
  - "sh -e /etc/init.d/xvfb start"
script: PADRINO_ENV=travis padrino rake

notifications:
  email:
    - hdmaidana@gmail.com
    - eugeniocalcena@gmail.com
    - cravacuore24@gmail.com
