language: ruby

before_install: gem install bundler --pre

bundler_args: --without development staging production

before_script:
  - "sh -e /etc/init.d/xvfb start"

script:
  - RACK_ENV=test
  - xvfb-run bundle exec padrino rake

rvm:
  - 1.9.3-p547

branches:
  only:
    - master
    - develop

notifications:
  email:
    - alvarez.ariel.work@gmail.com
    - javierperini90@gmail.com
    - rubini.marcelo@gmail.com
    - cravacuore24@gmail.com
